name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    permissions:
      pull-requests: read
      issues: read
      repository-projects: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: misspell
        uses: reviewdog/action-misspell@ce198e1db0d029be165f2d3e809c1a42353446b0
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          pattern: "*.md"
